# Generated by Django 5.2.8 on 2026-03-31 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0020_stock_cantidad_bloqueada_alter_stockproveedor_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de nota de entrega', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaEntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad a entregar')),
                ('cantidad_bloqueada', models.IntegerField(default=0, help_text='Cantidad bloqueada en inventario')),
                ('cual_costo', models.CharField(choices=[('costo', 'Costo Base'), ('costo_1', 'Costo 1 (10%)'), ('costo_2', 'Costo 2 (15%)'), ('costo_3', 'Costo 3 (25%)')], default='costo', help_text='Cuál precio usar para el cálculo', max_length=20)),
                ('precio_unitario_dolares', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario en dólares basado en cual_costo', max_digits=10)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reportes.notaentrega')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entrega', to='inventario.stock')),
                ('stock_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrega', to='inventario.stockproveedor')),
            ],
            options={
                'verbose_name': 'Item de Nota de Entrega',
                'verbose_name_plural': 'Items de Notas de Entrega',
            },
        ),
    ]
