# Generated by Django 5.2.8 on 2026-03-31 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('cedula', models.CharField(help_text='Cédula o RIF del cliente', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el cliente está activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrega', to='reportes.cliente'),
        ),
    ]
