# Generated by Django 5.2.12 on 2026-04-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_cliente_notaentrega_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaentregaitem',
            name='cual_costo',
            field=models.CharField(default='costo', help_text='Cuál precio usar para el cálculo', max_length=20),
        ),
    ]
