# Generated by Django 5.2.12 on 2026-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_costo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentregaitem',
            name='relacion_mts_ml_m2',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Relación MTS/ML/M² del stock', max_digits=10),
        ),
        migrations.AddField(
            model_name='notaentregaitem',
            name='tipo_venta',
            field=models.CharField(choices=[('cantidad', 'Por Cantidad'), ('mts_ml_m2', 'Por MTS/ML/M²')], default='cantidad', help_text='Cómo se vende: por cantidad o por MTS/ML/M²', max_length=20),
        ),
    ]
