# Generated by Django 5.2.8 on 2026-03-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_tres_porcentajes_utilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='consumible',
        ),
        migrations.RemoveField(
            model_name='epp',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='epp',
        ),
        migrations.DeleteModel(
            name='Consumible',
        ),
        migrations.DeleteModel(
            name='EPP',
        ),
    ]
