# Generated by Django 5.2.8 on 2026-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_movimientoinventario_consumible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
    ]
