# Generated by Django 5.2.8 on 2026-03-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_stock_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LugarConsumo',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
