# Generated by Django 5.2.8 on 2026-03-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_remove_lugar_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='costo_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='costo_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='envio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mts_ml_m2_3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='utilidad_15',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Usar StockProveedor en su lugar', max_digits=10),
        ),
        migrations.CreateModel(
            name='StockProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_preferido', models.BooleanField(default=False)),
                ('costo_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('envio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('utilidad_15', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mts_ml_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mts_ml_m2_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mts_ml_m2_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mts_ml_m2_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventario.proveedor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.stock')),
            ],
            options={
                'verbose_name': 'Stock Proveedor',
                'verbose_name_plural': 'Stocks Proveedores',
                'unique_together': {('stock', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='PrecioHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_historicos', to='inventario.movimientoinventario')),
                ('stock_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inventario.stockproveedor')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historiales de Precios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.stockproveedor'),
        ),
    ]
