# Generated by Django 5.2.12 on 2026-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_migrate_stock_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproveedor',
            name='costo_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockproveedor',
            name='costo_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockproveedor',
            name='costo_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
