# Generated by Django 5.2.12 on 2026-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_stockproveedor_costo_1_stockproveedor_costo_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='costo_dolares',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='costo_pesos',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mts_ml_m2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mts_ml_m2_1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mts_ml_m2_2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mts_ml_m2_3',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='utilidad_15',
        ),
        migrations.RemoveField(
            model_name='stockproveedor',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='stockproveedor',
            name='mts_ml_m2_1',
        ),
        migrations.RemoveField(
            model_name='stockproveedor',
            name='mts_ml_m2_2',
        ),
        migrations.RemoveField(
            model_name='stockproveedor',
            name='mts_ml_m2_3',
        ),
        migrations.RemoveField(
            model_name='stockproveedor',
            name='utilidad_15',
        ),
        migrations.AddField(
            model_name='stockproveedor',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo base en dólares', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Factor para convertir costo a mts/ml/m2 (ej: 2.5 para m²)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockproveedor',
            name='costo_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo con %1 (con factor si existe)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockproveedor',
            name='costo_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo con %2 (con factor si existe)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockproveedor',
            name='costo_3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo con %3 (con factor si existe)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockproveedor',
            name='mts_ml_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo transformado con factor 15%', max_digits=10, null=True),
        ),
    ]
