# Generated by Django 5.2.12 on 2026-03-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_stock_costo_remove_stock_costo_dolares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproveedor',
            old_name='costo_base',
            new_name='costo',
        ),
    ]
