# Generated by Django 5.2.8 on 2026-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_rename_costo_base_stockproveedor_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad_bloqueada',
            field=models.IntegerField(default=0, help_text='Cantidad bloqueada por notas de entrega pendientes'),
        ),
        migrations.AlterField(
            model_name='stockproveedor',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo transformado (en dólares)', max_digits=10),
        ),
    ]
