# Generated by Django 5.2.8 on 2026-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_vinculacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telegram_activo',
            field=models.BooleanField(default=False, help_text='Si el usuario quiere recibir notificaciones por Telegram'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
